### ISSUE TITLE
Misinterpreted structure building a keyless array

### ISSUE THREAD

**Issue by LigH-de** [KeldorDE/Lightweight-PHP-LUA-Parser#2]
The complex array structure in the file "RareTracker_data.lua" of the RIFT add-on "RareTracker" is not correctly interpreted, probably because it builds up a keyless array of arrays (which should result in an auto-incremented nummerical key).

http://rift.curseforge.com/addons/raretracker/
http://mods.curse.com/addons/rift/raretracker

The parser steps back one hierarchy level instead, and finally takes an opening brace as literal content instead of a start of a sub-array.

**Comment by KeldorDE** [comment]
Can you check this with the latest fix from #4, please?

**Comment by LigH-de** [comment]
In the meantime, this RIFT plugin (RareTracker) is obsolete (2 years are ages in game development, plugin authors disappear from the internet, and games add new content which is left uncovered), so I do not even have the script anymore which used to analyze this data, and eventually switched to a different plugin (MapExtension). That one is processed correctly on a format which describes a whole structure as explicit nested array.

Unfortunately, the MapExtension plugin stores the same data in a different format, incrementally, starting with an empty temporary array and adding one element after the other; then it assigns the exported variable to a special element in this temporary array which references all other elements in it ... there used to be a website - [RiftUtilz](http://riftutilz.com) - which was able to collect such files from many users, display the map coordinates in an interactive map, and offer the collection for download in the explicite structured format. Well. This website disappeared too, in the meantime.

I can send you the test files if you are still interested. But I am losing interest in my specific case as I am losing plugin developers providing current data I could use.

R.I.P.
